In [3]:
import os
import glob
import pandas as pd

### Select corresponding folder for each speed

In [4]:
def speed_to_folder(speed):
    if speed == 0.05232:
        return "3p6" # 1/0.4735 = 2.1193
    elif speed == 0.06528:
        return "4p4"
    elif speed == 0.06852:
        return "4p6"
    elif speed == 0.07824:
        return "5p2"
    elif speed == 0.09768:
        return "6p4"
    elif speed == 0.10092:
        return "6p6"
    elif speed == 0.11064:
        return "7p2"
    elif speed == 0.12036:
        return "7p8"
    elif speed == 0.13008:
        return "8p4"
    elif speed == 0.16248:
        return "10p4"
    elif speed == 0.17868:
        return "11p4"
    else:
        return "test"

In [15]:
folder = speed_to_folder(0.05232)
path = os.getcwd()
csv_files = glob.glob(os.path.join(f"/mnt/d/sources/data/DL-PTV/{folder}-1", "*.csv"))+glob.glob(os.path.join(f"/mnt/d/sources/data/DL-PTV/{folder}-2", "*.csv"))

In [ ]:
    def load_and_standardize_data(data_config):
    """Loads dataset from path"""
    data = []
    for speed in data_config.folders:
        data.append(pd.read_pickle(data_config.path + speed + ".pkl", compression="zip"))

    df = pd.concat(data, ignore_index=True)
    df = df.values.reshape(-1, df.shape[1])
    x_train = df[df[:, 6] != 0]
    x_test = df[df[:, 6] == 0]
    scalar = preprocessing.StandardScaler()
    x_train = scalar.fit_transform(x_train)
    x_test = scalar.transform(x_test)

    return x_train, x_test, scalar

In [17]:
def get_files_list(speed):
    folder = speed_to_folder(speed)
    # path = os.getcwd()
    csv_files = glob.glob(os.path.join(f"/mnt/d/sources/data/DL-PTV/{folder}-1", "*.csv"))+glob.glob(os.path.join(f"/mnt/d/sources/data/DL-PTV/{folder}-2", "*.csv"))
    # csv_files = glob.glob(os.path.join(path+f"/{folder}-1", "*.csv"))+glob.glob(os.path.join(path+f"/{folder}-2", "*.csv"))


    data = []
    for csv in csv_files:
        frame = pd.read_csv(csv, sep=";")
        frame['time'] = int(csv[-8:][:4])
        # frame['time']= frame['time']*8.25
        data.append(frame)

    df = pd.concat(data, ignore_index=True)
    df.columns=["x","y","z","vx","vy","vz","time"]
    # df["fv"] = speed
    # df = df[["fv","time","x","y","z","vx","vy","vz"]]
    return df

In [92]:
speed = 0.05232
df = get_files_list(speed)

In [20]:
df.to_csv(f"/mnt/d/sources/data/DL-PTV/merged/{speed_to_folder(speed)}.csv");

In [29]:
sppeds=[0.06528,0.06852,0.07824,0.09768,0.10092,0.11064,0.12036,0.13008,0.16248,0.17868]
for speed in sppeds:
    df = get_files_list(speed)
    df.to_pickle(f"/mnt/d/sources/data/DL-PTV/merged/{speed_to_folder(speed)}.pkl", compression='zip')

In [22]:
df.to_pickle(f"/mnt/d/sources/data/DL-PTV/merged/{speed_to_folder(speed)}.pkl", compression='zip')

In [23]:
new_df = pd.read_pickle(f"/mnt/d/sources/data/DL-PTV/merged/{speed_to_folder(speed)}.pkl", compression='zip')

In [93]:
test_data = df.iloc[100:300,:]
test_data.to_pickle(f"/mnt/d/sources/data/DL-PTV/merged/test1.pkl", compression='zip')

In [94]:
test_data = df.iloc[3000:3300,:]
test_data.to_pickle(f"/mnt/d/sources/data/DL-PTV/merged/test2.pkl", compression='zip')

In [95]:
test_data = df.iloc[8000:8300,:]
test_data.to_pickle(f"/mnt/d/sources/data/DL-PTV/merged/test3.pkl", compression='zip')

In [48]:
new_df.shape[1]

7

In [45]:
test_data.values.reshape(-1,7)

array([[-6.16840920e+01, -5.97116000e+01, -2.90972370e+01,
         1.71515000e-01, -2.89943200e-04, -2.36501100e-04,
         5.70000000e+01],
       [-5.77219160e+01, -5.97116000e+01, -2.90972370e+01,
         1.70899000e-01, -2.61071200e-06, -3.24674000e-04,
         5.70000000e+01],
       [-5.37597400e+01, -5.97116000e+01, -2.90972370e+01,
         1.69658000e-01, -1.03361800e-04, -7.82681100e-04,
         5.70000000e+01],
       [-4.97975640e+01, -5.97116000e+01, -2.90972370e+01,
         1.67861000e-01, -5.83022500e-04, -1.06800000e-03,
         5.70000000e+01],
       [-4.58353880e+01, -5.97116000e+01, -2.90972370e+01,
         1.65986000e-01, -1.41900000e-03, -4.49711600e-04,
         5.70000000e+01],
       [-4.18732120e+01, -5.97116000e+01, -2.90972370e+01,
         1.64646000e-01, -2.67700000e-03,  1.20100000e-03,
         5.70000000e+01],
       [-3.79110360e+01, -5.97116000e+01, -2.90972370e+01,
         1.64261000e-01, -4.53000000e-03,  2.71400000e-03,
         5.7000000

In [6]:
def concat_files1():
    speeds=[0.05232,0.06528]
    #     speeds=[0.05232,0.06528,0.06852,0.07824,0.09768,0.10092,0.11064,0.12036,0.13008,0.16248,0.17868]
    data = []
    for speed in speeds:
        new_df = get_files_list(speed)
        data.append(new_df)

    df = pd.concat(data, ignore_index=True)

    return df

In [7]:
# def concat_files():
#     speeds=[0.055555]
#     #     sppeds=[0.05232,0.06528,0.06852,0.07824,0.09768,0.10092,0.11064,0.12036,0.13008,0.16248,0.17868]
#     data = []
#     train_data = []
#     test_data = []
#
#     for speed in speeds:
#         train_sample = train_no(speed,0.8)
#         new_df = get_files_list(speed)
#         train_df = new_df[new_df['time']<=train_sample]
#         test_df = new_df[new_df['time']>train_sample]
#         train_data.append(train_df)
#         test_data.append(test_df)
#
#     df_train = pd.concat(train_data, ignore_index=True)
#     df_test = pd.concat(test_data, ignore_index=True)
#
#     return df_train.to_numpy(dtype='float64'), df_test.to_numpy(dtype='float64')

In [72]:
df

x          y          z        vx        vy        vz  time
0    17.559430  82.926739 -33.059413  0.169153  0.004961  0.000826     1
1    21.521606  82.926739 -33.059413  0.168211  0.006639  0.003873     1
2    25.483782  82.926739 -33.059413  0.167201  0.008493  0.003999     1
3    29.445958  82.926739 -33.059413  0.166278  0.010426  0.001571     1
4    33.408134  82.926739 -33.059413  0.165591  0.012348 -0.002446     1
..         ...        ...        ...       ...       ...       ...   ...
295  61.143366 -63.673777 -29.097237  0.178601  0.008066  0.000431    10
296  65.105543 -63.673777 -29.097237  0.176030  0.009014  0.002814    10
297  69.067719 -63.673777 -29.097237  0.173915  0.009448  0.003826    10
298  73.029895 -63.673777 -29.097237  0.172293  0.009541  0.003881    10
299  76.992071 -63.673777 -29.097237  0.170998  0.009530  0.004145    10

[300 rows x 7 columns]

In [68]:
a=0
b=1
for d in [30,60,90,120,150,180,210,240,270,300]:
    df.loc[a:d,"time"]=b
    a=d+1
    b=b+1

In [99]:
path = "/mnt/d/sources/data/DL-PTV/merged/"
data = []
for speed in ["test1", "test2","test3"]:
    data.append(pd.read_pickle(path+speed+".pkl",compression="zip"))

df = pd.concat(data,ignore_index=True)
a=0
b=1
for d in [30,60,90,120,150,180,210,240,270,300,330,360,390,410,440,470,500,530,560,590,620,650,680,710,740,770,800]:
    df.loc[a:d,"time"]=b
    a=d+1
    b=b+1


df.to_pickle(f"/mnt/d/sources/data/DL-PTV/merged/test.pkl", compression='zip')

In [100]:
df

x          y          z        vx        vy        vz  time
0    17.559430  82.926739 -33.059413  0.049695  0.000709  0.005559     1
1    21.521606  82.926739 -33.059413  0.049391  0.000787  0.005296     1
2    25.483782  82.926739 -33.059413  0.049173  0.000950  0.004962     1
3    29.445958  82.926739 -33.059413  0.049061  0.001139  0.004679     1
4    33.408134  82.926739 -33.059413  0.049037  0.001287  0.004625     1
..         ...        ...        ...       ...       ...       ...   ...
795  29.445958 -75.560305 -25.135060  0.048628 -0.000126  0.002526    27
796  33.408134 -75.560305 -25.135060  0.047847 -0.000577  0.000994    27
797  37.370310 -75.560305 -25.135060  0.047356 -0.001204 -0.000762    27
798  41.332486 -75.560305 -25.135060  0.047215 -0.001870 -0.002081    27
799  45.294662 -75.560305 -25.135060  0.047326 -0.002472 -0.002694    27

[800 rows x 7 columns]

In [84]:
path = "/mnt/d/sources/data/DL-PTV/merged/"
data = []
for speed in ["test1", "test2","test3"]:
    data.append(pd.read_pickle(path+speed+".pkl",compression="zip"))

df = pd.concat(data,ignore_index=True)
a=0
b=1
for d in [30,60,90,120,150,180,210,240,270,300]:
    df.loc[a:d,"time"]=b
    a=d+1
    b=b+1
df = df.values.reshape(-1, df.shape[1])
X_train = df[df[:,6]%2!=0]
X_test = df[df[:,6]%2==0]


# df[::2]
# df[1::2]

In [85]:
X_test

array([[-1.13192381e+02,  7.89645630e+01, -3.30594130e+01, ...,
         1.46510000e-02,  1.01330000e-02,  2.00000000e+00],
       [-1.09230205e+02,  7.89645630e+01, -3.30594130e+01, ...,
         1.41420000e-02,  1.20950000e-02,  2.00000000e+00],
       [-1.05268029e+02,  7.89645630e+01, -3.30594130e+01, ...,
         1.34130000e-02,  1.38210000e-02,  2.00000000e+00],
       ...,
       [ 6.90677190e+01, -6.36737770e+01, -2.90972370e+01, ...,
         9.44800000e-03,  3.82600000e-03,  1.00000000e+01],
       [ 7.30298950e+01, -6.36737770e+01, -2.90972370e+01, ...,
         9.54100000e-03,  3.88100000e-03,  1.00000000e+01],
       [ 7.69920710e+01, -6.36737770e+01, -2.90972370e+01, ...,
         9.53000000e-03,  4.14500000e-03,  1.00000000e+01]])

In [86]:
X_train

array([[ 1.7559430e+01,  8.2926739e+01, -3.3059413e+01, ...,
         4.9610000e-03,  8.2596680e-04,  1.0000000e+00],
       [ 2.1521606e+01,  8.2926739e+01, -3.3059413e+01, ...,
         6.6390000e-03,  3.8730000e-03,  1.0000000e+00],
       [ 2.5483782e+01,  8.2926739e+01, -3.3059413e+01, ...,
         8.4930000e-03,  3.9990000e-03,  1.0000000e+00],
       ...,
       [-4.5835388e+01, -6.3673777e+01, -2.9097237e+01, ...,
        -1.9190000e-03,  2.8210000e-03,  9.0000000e+00],
       [-4.1873212e+01, -6.3673777e+01, -2.9097237e+01, ...,
        -2.1410000e-03,  4.3440000e-03,  9.0000000e+00],
       [-3.7911036e+01, -6.3673777e+01, -2.9097237e+01, ...,
        -2.7710000e-03,  5.6550000e-03,  9.0000000e+00]])